language: ruby
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3.1
  - 2.4.2
  - 2.6.4
  - jruby-9.2
before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'
